# docker-compose.test.yml
version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=test
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
